import type { Category, Job, Recruiter, Worker, ChatThread } from "./types";

export const categoryMeta: Record<Category, { icon: string; en: string; hi: string; ta: string }> = {
  security: { icon: "🛡️", en: "Security Guard", hi: "सिक्योरिटी गार्ड", ta: "பாதுகாப்பு" },
  driver: { icon: "🚗", en: "Driver", hi: "ड्राइवर", ta: "ஓட்டுநர்" },
  electrician: { icon: "⚡", en: "Electrician", hi: "इलेक्ट्रीशियन", ta: "மின்சாரத் தொழிலாளி" },
  plumber: { icon: "🔧", en: "Plumber", hi: "प्लम्बर", ta: "குழாய் பழுது" },
  maid: { icon: "🧹", en: "Maid", hi: "घरेलू सहायिका", ta: "வீட்டுப் பணிப்பெண்" },
  cook: { icon: "🍳", en: "Cook", hi: "कुक", ta: "சமையல்காரர்" },
  carpenter: { icon: "🪚", en: "Carpenter", hi: "कारपेंटर", ta: "தச்சர்" },
  delivery: { icon: "📦", en: "Delivery", hi: "डिलीवरी", ta: "டெலிவரி" },
  nanny: { icon: "👶", en: "Nanny", hi: "नैनी", ta: "குழந்தை பராமரிப்பு" },
  housekeeping: { icon: "🏨", en: "Housekeeping", hi: "हाउसकीपिंग", ta: "வீட்டு பராமரிப்பு" },
};

export const recruiters: Recruiter[] = [
  { id: "r1", name: "Mrs. Kapoor", org: "Sunrise Apartments", emoji: "🏢", verified: true, rating: 4.8, phone: "9876500001" },
  { id: "r2", name: "Sharma & Sons", org: "Sharma Hardware", emoji: "🛠️", verified: true, rating: 4.5, phone: "9876500002" },
  { id: "r3", name: "Priya Nair", org: "Homeowner", emoji: "🏠", verified: false, rating: 4.2, phone: "9876500003" },
];

export const workers: Worker[] = [
  { id: "w1", name: "Sunita Devi", emoji: "👩", category: "maid", area: "Lajpat Nagar", distanceKm: 1.2, rating: 4.8, reviews: 34, experience: "5+ years", verified: true, available: true, langs: ["hi"], phone: "9876543210" },
  { id: "w2", name: "Ramesh Kumar", emoji: "👨‍🔧", category: "electrician", area: "Saket", distanceKm: 2.5, rating: 4.6, reviews: 21, experience: "3-5 years", verified: true, available: true, langs: ["hi", "en"], phone: "9876543211" },
  { id: "w3", name: "Mohan Singh", emoji: "🧔", category: "plumber", area: "Hauz Khas", distanceKm: 3.1, rating: 4.4, reviews: 17, experience: "1-2 years", verified: false, available: true, langs: ["hi"], phone: "9876543212" },
  { id: "w4", name: "Anjali Sharma", emoji: "👩‍🍳", category: "cook", area: "GK-2", distanceKm: 0.8, rating: 4.9, reviews: 52, experience: "5+ years", verified: true, available: false, langs: ["hi", "en"], phone: "9876543213" },
  { id: "w5", name: "Vijay Kumar", emoji: "👨‍✈️", category: "driver", area: "Vasant Kunj", distanceKm: 4.2, rating: 4.7, reviews: 29, experience: "5+ years", verified: true, available: true, langs: ["hi", "en"], phone: "9876543214" },
  { id: "w6", name: "Priya Devi", emoji: "👩‍👧", category: "nanny", area: "Dwarka", distanceKm: 5.0, rating: 4.5, reviews: 11, experience: "1-2 years", verified: true, available: true, langs: ["hi"], phone: "9876543215" },
  { id: "w7", name: "Karthik R.", emoji: "👨", category: "security", area: "Anna Nagar", distanceKm: 1.8, rating: 4.6, reviews: 24, experience: "3-5 years", verified: true, available: true, langs: ["ta", "hi"], phone: "9876543216" },
];

// Seed jobs come with pre-baked AI outputs so the demo works even offline.
export const seedJobs: Job[] = [
  {
    id: "j1",
    category: "security",
    title: "Security Guard — Sunrise Apartments",
    recruiterId: "r1",
    salaryType: "monthly",
    salaryMin: 18000,
    salaryMax: 22000,
    area: "Dwarka Sector 12",
    pincode: "110075",
    distanceKm: 2.1,
    shift: "rotational",
    workingDays: "6 days/week",
    gender: "male",
    ageMin: 25,
    ageMax: 50,
    experience: "2+ years",
    verificationRequired: true,
    requirements: "Seeking experienced residential security personnel for rotational shifts. Strong surveillance capabilities and visitor management required.",
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    verified: true,
    simplified: {
      hi: `हमें एक सिक्योरिटी गार्ड चाहिए।\n\n📍 जगह: द्वारका, सेक्टर 12\n💰 वेतन: ₹18,000 – ₹22,000 प्रति माह\n🕒 ड्यूटी: दिन और रात दोनों शिफ्ट हो सकती हैं\n🛡 काम: सोसायटी में आने-जाने वाले लोगों पर नज़र रखना और सुरक्षा सुनिश्चित करना\n👤 अनुभव: कम से कम 2 साल\n\nअगर आप यह काम कर सकते हैं तो आवेदन करें।`,
      en: `We need a Security Guard.\n\n📍 Place: Dwarka Sector 12\n💰 Pay: ₹18,000 – ₹22,000 per month\n🕒 Duty: Both day and night shifts possible\n🛡 Work: Watch people entering and leaving the society, keep everyone safe\n👤 Experience: At least 2 years\n\nIf you can do this work, please apply.`,
      ta: `எங்களுக்கு ஒரு பாதுகாவலர் தேவை.\n\n📍 இடம்: துவாரகா, செக்டார் 12\n💰 சம்பளம்: ₹18,000 – ₹22,000 மாதம்\n🕒 பணி: பகல் மற்றும் இரவு ஷிப்ட்\n🛡 வேலை: வரும் போகும் நபர்களை கவனிப்பது, பாதுகாப்பை உறுதி செய்வது\n👤 அனுபவம்: குறைந்தது 2 ஆண்டுகள்\n\nஉங்களால் முடியும் என்றால் விண்ணப்பிக்கவும்.`,
    },
    summary: {
      highlights: ["₹18,000–22,000 monthly", "📍 2 km away", "🕒 Full time", "⭐ Verified employer"],
      bestFor: ["Experienced guards", "Ex-army personnel", "Security agency workers"],
      thingsToKnow: ["Night shifts may be required", "Standing for long hours", "Uniform provided"],
      benefits: ["Stable monthly salary", "Local workplace", "Long-term opportunity"],
    },
  },
  {
    id: "j2",
    category: "maid",
    title: "Maid — 2 BHK Flat",
    recruiterId: "r3",
    salaryType: "monthly",
    salaryMin: 8000,
    salaryMax: 10000,
    area: "Greater Kailash II",
    pincode: "110048",
    distanceKm: 0.9,
    shift: "part",
    workingDays: "Mon–Sat",
    gender: "female",
    ageMin: 25,
    ageMax: 50,
    experience: "1-2 years",
    verificationRequired: true,
    requirements: "Need a maid for cleaning, utensils, basic cooking. 2 hours morning, 1 hour evening.",
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    verified: true,
    simplified: {
      hi: `हमें घरेलू सहायिका चाहिए।\n\n📍 जगह: GK-2\n💰 वेतन: ₹8,000 – ₹10,000 प्रति माह\n🕒 समय: सुबह 2 घंटे, शाम 1 घंटा\n🧹 काम: सफाई, बर्तन, थोड़ा खाना बनाना\n👤 अनुभव: 1-2 साल\n\nपास रहने वाली बहनें आवेदन करें।`,
      en: `We need a maid.\n\n📍 Place: GK-2\n💰 Pay: ₹8,000 – ₹10,000 per month\n🕒 Time: 2 hrs morning, 1 hr evening\n🧹 Work: Cleaning, utensils, light cooking\n👤 Experience: 1-2 years\n\nLadies living nearby please apply.`,
      ta: `வீட்டுப் பணிப்பெண் தேவை.\n\n📍 இடம்: GK-2\n💰 சம்பளம்: ₹8,000 – ₹10,000\n🕒 நேரம்: காலை 2 மணி, மாலை 1 மணி\n🧹 வேலை: சுத்தம், பாத்திரம், சிறு சமையல்\n👤 அனுபவம்: 1-2 ஆண்டுகள்\n\nஅருகில் வசிப்பவர்கள் விண்ணப்பிக்கவும்.`,
    },
    summary: {
      highlights: ["₹8,000–10,000 monthly", "📍 0.9 km away", "🕒 Part time", "⭐ Trusted family"],
      bestFor: ["Local women workers", "Part-time seekers", "Maids with cleaning experience"],
      thingsToKnow: ["Split shift (morning + evening)", "Light cooking required", "ID verification needed"],
      benefits: ["Walking distance", "Friendly family", "Fixed monthly pay"],
    },
  },
  {
    id: "j3",
    category: "driver",
    title: "Personal Driver — Sedan",
    recruiterId: "r2",
    salaryType: "monthly",
    salaryMin: 20000,
    salaryMax: 25000,
    area: "Vasant Kunj",
    pincode: "110070",
    distanceKm: 3.4,
    shift: "day",
    workingDays: "Mon–Sat",
    gender: "male",
    ageMin: 25,
    ageMax: 45,
    experience: "3-5 years",
    verificationRequired: true,
    requirements: "Personal sedan driver, must know Delhi-NCR routes, valid DL, polite, punctual.",
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    verified: true,
    simplified: {
      hi: `हमें कार ड्राइवर चाहिए।\n\n📍 जगह: वसंत कुंज\n💰 वेतन: ₹20,000 – ₹25,000 प्रति माह\n🕒 समय: सुबह से शाम (दिन की शिफ्ट)\n🚗 काम: निजी कार चलाना, परिवार को ले जाना-लाना\n👤 अनुभव: 3-5 साल, लाइसेंस ज़रूरी\n\nदिल्ली के रास्ते जानते हों तो आवेदन करें।`,
      en: `We need a car driver.\n\n📍 Place: Vasant Kunj\n💰 Pay: ₹20,000 – ₹25,000 per month\n🕒 Time: Morning to evening (day shift)\n🚗 Work: Drive personal sedan, ferry family\n👤 Experience: 3-5 yrs, valid licence required\n\nApply if you know Delhi routes.`,
      ta: `கார் ஓட்டுநர் தேவை.\n\n📍 இடம்: வசந்த் குஞ்ச்\n💰 சம்பளம்: ₹20,000 – ₹25,000\n🕒 நேரம்: காலை முதல் மாலை வரை\n🚗 வேலை: தனிப்பட்ட காரை ஓட்டுவது\n👤 அனுபவம்: 3-5 ஆண்டுகள், உரிமம் கட்டாயம்\n\nடெல்லி வழிகள் தெரிந்தால் விண்ணப்பிக்கவும்.`,
    },
    summary: {
      highlights: ["₹20,000–25,000 monthly", "📍 3.4 km away", "🕒 Day shift", "⭐ Verified family"],
      bestFor: ["Experienced sedan drivers", "Ola/Uber drivers seeking stability", "Drivers with NCR routes"],
      thingsToKnow: ["Valid driving licence mandatory", "Sundays off", "Punctuality required"],
      benefits: ["Stable monthly pay", "No outstation travel", "Polite family"],
    },
  },
  {
    id: "j4",
    category: "electrician",
    title: "Electrician — Daily Wage",
    recruiterId: "r2",
    salaryType: "daily",
    salaryMin: 600,
    salaryMax: 800,
    area: "Saket",
    pincode: "110017",
    distanceKm: 2.5,
    shift: "day",
    workingDays: "On call",
    gender: "any",
    ageMin: 20,
    ageMax: 50,
    experience: "1-2 years",
    verificationRequired: false,
    requirements: "Wiring, switch boards, MCB, fan/AC installation. Hardware shop will provide tools.",
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    verified: true,
    simplified: {
      hi: `हमें इलेक्ट्रीशियन चाहिए (दैनिक काम)।\n\n📍 जगह: साकेत\n💰 वेतन: ₹600 – ₹800 प्रति दिन\n🕒 समय: दिन का काम, ज़रूरत पर बुलाएँगे\n⚡ काम: वायरिंग, स्विच, MCB, पंखा/AC लगाना\n👤 अनुभव: 1-2 साल\n\nऔज़ार हम देंगे। तुरंत शुरू कर सकते हैं।`,
      en: `We need an electrician (daily work).\n\n📍 Place: Saket\n💰 Pay: ₹600 – ₹800 per day\n🕒 Time: Day work, on call\n⚡ Work: Wiring, switches, MCB, fan/AC installation\n👤 Experience: 1-2 years\n\nTools provided. Immediate start.`,
      ta: `மின்சாரத் தொழிலாளி தேவை (தினசரி).\n\n📍 இடம்: சாக்கேத்\n💰 சம்பளம்: ₹600 – ₹800 / நாள்\n🕒 நேரம்: பகல், கேட்கும் போது\n⚡ வேலை: வயரிங், சுவிட்ச், MCB, மின்விசிறி/AC\n👤 அனுபவம்: 1-2 ஆண்டுகள்\n\nகருவிகள் தருகிறோம்.`,
    },
    summary: {
      highlights: ["₹600–800 per day", "📍 2.5 km away", "🛠 Tools provided", "⚡ Immediate start"],
      bestFor: ["Daily-wage electricians", "Helpers wanting to grow", "On-call workers"],
      thingsToKnow: ["No fixed monthly salary", "On-call basis", "Travel within Saket area"],
      benefits: ["Quick payment", "Flexible days", "Tools provided"],
    },
  },
];

export const seedChats: ChatThread[] = [
  {
    id: "c1",
    name: "Mrs. Kapoor",
    emoji: "🏢",
    role: "Sunrise Apartments",
    messages: [
      { id: "m1", from: "them", text: "नमस्ते, क्या आप कल आ सकते हैं इंटरव्यू के लिए?", at: "10:20 AM" },
      { id: "m2", from: "me", text: "जी मैडम, सुबह 9 बजे आ जाऊँगा 🙏", at: "10:30 AM" },
    ],
  },
  {
    id: "c2",
    name: "Sharma & Sons",
    emoji: "🛠️",
    role: "Sharma Hardware",
    messages: [
      { id: "m1", from: "them", text: "AC installation आज हो जाएगा?", at: "Yesterday" },
      { id: "m2", from: "me", text: "हाँ, ₹600 लगेंगे, शाम 5 बजे पहुँचूँगा", at: "Yesterday" },
    ],
  },
];
